export const ui = {
  // ── Signed-out page ──────────────────────────────────────────────────────
  signedOutPage: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    background: "#f8fafc",
  },
  signedOutInner: {
    maxWidth: 400,
    width: "100%",
    padding: "0 20px",
  },
  signedOutTitle: {
    fontSize: 28,
    fontWeight: 700,
    color: "#0f172a",
    letterSpacing: "-0.03em",
    marginBottom: 4,
  },
  signedOutSubtitle: {
    fontSize: 14,
    color: "#64748b",
    marginTop: 0,
    marginBottom: 28,
  },
  signedOutCard: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 14,
    padding: "24px 20px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
  },

  // ── Authenticated shell ───────────────────────────────────────────────────
  shell: {
    marginLeft: 220,
    minHeight: "100vh",
    background: "#f8fafc",
  },

  // ── Sidebar ───────────────────────────────────────────────────────────────
  sidebar: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    width: 220,
    height: "100vh",
    background: "#ffffff",
    borderRight: "1px solid #e2e8f0",
    display: "flex",
    flexDirection: "column" as const,
    zIndex: 20,
    overflow: "hidden",
  },
  sidebarHeader: {
    padding: "20px 20px 14px",
    borderBottom: "1px solid #f1f5f9",
    flexShrink: 0,
  },
  sidebarAppName: {
    fontSize: 20,
    fontWeight: 700,
    color: "#0f172a",
    margin: 0,
    letterSpacing: "-0.03em",
  },
  sidebarEmail: {
    fontSize: 12,
    color: "#94a3b8",
    margin: "4px 0 0",
    overflow: "hidden" as const,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  navList: {
    flex: 1,
    padding: "6px 0",
    listStyle: "none",
    margin: 0,
    flexShrink: 1,
    overflow: "hidden",
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 16px",
    fontSize: 14,
    color: "#374151",
    cursor: "pointer",
    border: "none",
    background: "none",
    width: "100%",
    textAlign: "left" as const,
    borderLeft: "3px solid transparent",
    fontFamily: "inherit",
    textDecoration: "none",
    lineHeight: 1.4,
  },
  navItemActive: {
    color: "#2563eb",
    background: "#eff6ff",
    borderLeft: "3px solid #2563eb",
    fontWeight: 600,
  },
  navItemDisabled: {
    color: "#c8d5e3",
    cursor: "default" as const,
    pointerEvents: "none" as const,
  },
  navBadge: {
    fontSize: 10,
    background: "#f1f5f9",
    color: "#b0bec5",
    borderRadius: 4,
    padding: "1px 5px",
    marginLeft: "auto",
    fontWeight: 500,
    letterSpacing: "0.01em",
  },
  sidebarFooter: {
    padding: "12px 20px",
    borderTop: "1px solid #f1f5f9",
    flexShrink: 0,
  },
  signOutBtn: {
    background: "none",
    border: "none",
    color: "#ef4444",
    fontSize: 13,
    cursor: "pointer",
    padding: 0,
    fontFamily: "inherit",
  },

  // ── Main content ──────────────────────────────────────────────────────────
  mainContent: {
    display: "flex",
    flexDirection: "column" as const,
    minHeight: "100vh",
  },
  topBar: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "0 24px",
    height: 56,
    background: "#ffffff",
    borderBottom: "1px solid #e2e8f0",
    position: "sticky" as const,
    top: 0,
    zIndex: 10,
    flexShrink: 0,
  },
  topBarTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: "#0f172a",
    margin: 0,
    flex: 1,
    letterSpacing: "-0.03em",
  },
  searchWrapper: {
    position: "relative" as const,
    display: "flex",
    alignItems: "center",
  },
  searchIcon: {
    position: "absolute" as const,
    left: 10,
    top: "50%",
    transform: "translateY(-50%)",
    color: "#94a3b8",
    pointerEvents: "none" as const,
    display: "flex",
  },
  topBarSearch: {
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "7px 10px 7px 34px",
    fontSize: 13,
    background: "#f8fafc",
    width: 240,
    fontFamily: "inherit",
    color: "#0f172a",
    outline: "none",
  },
  composeSection: {
    padding: "14px 24px",
    background: "#f8fafc",
    borderBottom: "1px solid #e2e8f0",
    flexShrink: 0,
  },
  composeSectionTitle: {
    margin: "0 0 10px",
    fontSize: 13,
    fontWeight: 600,
    color: "#374151",
  },
  mainBody: {
    padding: 24,
    flex: 1,
  },

  // ── List card ─────────────────────────────────────────────────────────────
  listCard: {
    background: "#ffffff",
    borderRadius: 12,
    border: "1px solid #e2e8f0",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
    overflow: "hidden",
  },
  listCardFooter: {
    padding: "10px 16px",
    fontSize: 13,
    color: "#94a3b8",
    borderTop: "1px solid #f1f5f9",
  },
  contactRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "0 16px",
    height: 48,
    borderBottom: "1px solid #f1f5f9",
  },
  contactRowActions: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 16px 12px 60px",
    borderBottom: "1px solid #f1f5f9",
    flexWrap: "wrap" as const,
    gap2: 6,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "#dbeafe",
    color: "#1d4ed8",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 600,
    flexShrink: 0,
    letterSpacing: "0.01em",
  },
  iconButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px 6px",
    color: "#94a3b8",
    display: "flex",
    alignItems: "center",
    borderRadius: 6,
    fontFamily: "inherit",
    flexShrink: 0,
  },

  // ── Feedback banner ───────────────────────────────────────────────────────
  feedbackBanner: {
    padding: "10px 24px",
    fontSize: 13,
    borderBottom: "1px solid #e2e8f0",
    flexShrink: 0,
  },

  // ── Form primitives ───────────────────────────────────────────────────────
  input: {
    width: "100%",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "9px 12px",
    background: "#ffffff",
    boxSizing: "border-box" as const,
    fontFamily: "inherit",
    fontSize: 14,
    color: "#0f172a",
    outline: "none",
  },
  compactInput: {
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "8px 12px",
    background: "#ffffff",
    boxSizing: "border-box" as const,
    fontFamily: "inherit",
    fontSize: 14,
    color: "#0f172a",
    outline: "none",
  },
  primaryButton: {
    border: "1px solid #2563eb",
    background: "#2563eb",
    color: "#ffffff",
    borderRadius: 8,
    padding: "8px 14px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 14,
    fontWeight: 500,
    whiteSpace: "nowrap" as const,
  },
  secondaryButton: {
    border: "1px solid #e2e8f0",
    background: "#f8fafc",
    color: "#374151",
    borderRadius: 8,
    padding: "8px 14px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 14,
    fontWeight: 500,
    whiteSpace: "nowrap" as const,
  },
  smallButton: {
    border: "1px solid #e2e8f0",
    background: "#f8fafc",
    color: "#374151",
    borderRadius: 6,
    padding: "4px 10px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 500,
    whiteSpace: "nowrap" as const,
  },

  // ── Labels ────────────────────────────────────────────────────────────────
  labelPill: {
    fontSize: 11,
    borderRadius: 4,
    padding: "2px 7px",
    fontWeight: 500,
    whiteSpace: "nowrap" as const,
  },

  // ── Legacy tokens (kept for signed-out / manage-labels usage) ─────────────
  row: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap" as const,
  },
  sectionHint: {
    marginTop: 0,
    color: "#64748b",
    fontSize: 13,
  },
};

export function feedbackColor(tone: "error" | "success" | "info") {
  if (tone === "error") return "#b91c1c";
  if (tone === "success") return "#166534";
  return "#0f766e";
}
